JP/DBWT Paket 5/DBWT Paket 5/Controllers/DetailsController.cs
using DBWT_Paket_5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBWT_Paket_5.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult Index(string id)
        {
            int t = Convert.ToInt32(id);
          
            if (t < 0 || t > 8) { return View("~/Views/Details/FailID.cshtml"); }
            else
            {
                var p = Produkt.detail(t);
           
                ViewData["MyP"] = p;
                return View();
            }
        }

        // GET: Details/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Details/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Details/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Details/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Details/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Details/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Details/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JP/DBWT Paket 5/DBWT Paket 5/Views/Shared/_BELayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>

 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Style/BEStyle.css" rel="stylesheet">
</head>
<body>

    <div class="container">
        jkadklfmsdf
        <div class="col-md-2"><h1><b>e-Mensa</b></h1></div>
        <div class="col-md-5" style="padding-top:25px;">
            <nav>
                <ul class="nav nav-pills unterstriche">
                    <li>
                        <a href="@Url.Action("Index", "Home")">Start</a>
                    </li>
                    <li>
                        <a href="@Url.Action("xmlsite", "Home")">Mahlzeiten</a>
                    </li>
                    <li>
                        <a href="@Url.Action("IndexDetails", "Details")">Bestellung</a>
                    </li>
                    <li>
                        <a href="http://www.fh-aachen.de" target="_blank">FH-Aachen</a>
                    </li>

                </ul>
            </nav>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3" style="padding-top:25px;">
            <form action="http://www.google.de/search">
                <input type="hidden" name="as_sitesearch" value="www.fh-aachen.de" />
                <input name="q" type="search" placeholder="FH-Suche" />
                <button type="submit">Suche</button>
            </form>

        </div>

        <div class="col-md-12"><hr /></div>
    </div>



    @RenderBody()
    <div class="container">
        <div class="col-md-12"><hr /></div>
        <div class="col-md-2"><h4>(c) 2017 DBWT</h4></div>
        <div class="col-md-10">
            <nav>
                <ul class="nav nav-pills unterstriche">
                    <li>
                        <a href="#">Login</a>
                    </li>
                    <li>
                        <a href="#">Registrieren</a>
                    </li>
                    <li>
                        <a href="#">Zutatenliste</a>
                    </li>
                    <li>
                        <a href="~/Impressum.cshtml">Impressum</a>
                    </li>
                    <li>
                        @{
                            var date = DateTime.Now;
                        }
                        @date
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</body>
</html>

JP/DBWT Paket 5/DBWT Paket 5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>

   
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">
        <div class="col-md-2"><h1><b>e-Mensa</b></h1></div>
        <div class="col-md-5" style="padding-top:25px;">
            <nav>
                <ul class="nav nav-pills unterstriche">
                    <li>
                        <a href="@Url.Action("Index", "Home")">Start</a>
                    </li>
                    <li>
                        <a href="@Url.Action("xmlsite", "Home")">Mahlzeiten</a>
                    </li>
                    <li>
                        <a href="@Url.Action("IndexDetails", "Details")">Bestellung</a>
                    </li>
                    <li>
                        <a href="http://www.fh-aachen.de" target="_blank">FH-Aachen</a>
                    </li>

                </ul>
            </nav>
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-3" style="padding-top:25px;">
            <form action="http://www.google.de/search">
                <input type="hidden" name="as_sitesearch" value="www.fh-aachen.de" />
                <input name="q" type="search" placeholder="FH-Suche" />
                <button type="submit">Suche</button>
            </form>

        </div>

        <div class="col-md-12"><hr /></div>
    </div>

 

    @RenderBody()
    <div class="container">
        <div class="col-md-12"><hr /></div>
        <div class="col-md-2"><h4>(c) 2017 DBWT</h4></div>
        <div class="col-md-10">
            <nav>
                <ul class="nav nav-pills unterstriche">
                    <li>
                        <a href="#">Login</a>
                    </li>
                    <li>
                        <a href="#">Registrieren</a>
                    </li>
                    <li>
                        <a href="#">Zutatenliste</a>
                    </li>
                    <li>
                        <a href="~/Impressum.cshtml">Impressum</a>
                    </li>
                    <li>
                        @{
                            var date = DateTime.Now;
                        }
                        @date
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</body>
</html>