JP/DBWT Paket 5/DBWT Paket 5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using LinqToDB;
using System.Web.Mvc;
using DBWT_Paket_5.Models;
using DataModels;
using System.Xml.Linq;
using System.Xml.XPath;

namespace DBWT_Paket_5.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            bool isbackend = false;
            Login be = new Login();
            if (!string.IsNullOrEmpty(Session["name"] as string)){
                isbackend = be.isBE(Session["name"].ToString());
                
            }
            if (isbackend) { return RedirectToAction("Backend"); }
            else  return View();
        }

        // GET: Home/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        public ActionResult Backend()
        {
            using (var db = new DataModels.PraktikumDB())
            {
                //LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;

                // letzter login
                var q = from z in db.FeNutzer
                        where z.Aktiv != false
                        select z;

                // letzte registrierung
                var qq = from z in db.FeNutzer
                         where z.Aktiv == false
                         select z;

                // Sortiert und ein Limit von nur 5
                q = q.OrderByDescending(z => z.LetzterLogin).Take(5);
                qq = qq.OrderByDescending(z => z.LetzterLogin).Take(5);

                ViewBag.llogin_rollen = q.ToList();
                ViewBag.lregistrierung_rollen = qq.ToList();
            }
            return View();
        }
        // GET: Home/Create
        public ActionResult aktivieren(int id = 0)
        {
            using (var db = new DataModels.PraktikumDB())
            {
                //LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
                DataModels.FeNutzer fe = db.FeNutzer.Find(Convert.ToUInt32(id));

                fe.Aktiv = true;

                db.Update(fe);
            }
            return RedirectToAction("Backend");
        }
        public ActionResult deaktivieren(int id = 0)
        {
            using (var db = new DataModels.PraktikumDB())
            {
                //LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
                DataModels.FeNutzer fe = db.FeNutzer.Find(Convert.ToUInt32(id));
                if (fe.Loginname != "wardaschka")
                {
                    fe.Aktiv = false;
                }
                db.Update(fe);
            }
            return RedirectToAction("Backend");
         

        }
        public ActionResult xmlsite()
        {
            Benutzer person = new Benutzer();
            List<XElement> l = null;
            var doc = XDocument.Load(Server.MapPath("~/App_Data/Speiseplan.xml"));
            XElement root = doc.Root;
            var q = from z in root.Descendants("Menu")
                    select z;
            var db = new DataModels.PraktikumDB();
            Datenverarbeitung dv = new Datenverarbeitung();
            foreach (var v in q.Elements("Produkte").Elements("Produkt"))
            {
               
                bool has = db.Produkts.Any(p => p.ID == Convert.ToInt32(v.Attribute("ProduktID").Value));
                if (!has)
                {
                    v.Remove();
                }
            }

            foreach (var v in q.Elements("Produkte").Elements("Produkt"))
            {
                bool has = db.Produkts.Any(p => p.ID == Convert.ToInt32(v.Attribute("ProduktID").Value));
                if (!has)
                {
                    v.Remove();
                }
            }

            foreach (var v in q.Elements("Produkte").Elements("Produkt"))
            {
                DataModels.Produkt p1 = db.Produkts.FirstOrDefault(p => p.ID == Convert.ToInt32(v.Attribute("ProduktID").Value));
                Bild p2 = db.Bilds.FirstOrDefault(p => p.Id == p1.Bildid);
                Preis p3 = db.Preis.FirstOrDefault(p => p.ID == p1.Bildid);
                XElement x = null;
                XElement xx = null;

                if (v.Parent.Parent.Attribute("Highlight") != null)
                {
                    x = new XElement("Bild", dv.blobToBase64(p2.Binaerdaten));
                    v.Add(x);
                }

                if (person.id != 0)
                {
                    if (person.rolle == "student")
                    {
                        x = new XElement("preisVon", "Student");
                        xx = new XElement("anzeigePreis", p3.Studentenbetrag.ToString("C"));
                    }
                    if (person.rolle == "mitarbeiter")
                    {
                        x = new XElement("preisVon", "Mitarbeiter");
                        xx = new XElement("anzeigePreis", p3.Mitarbeiterbetrag.ToString("C"));
                    }
                    if (person.rolle == "gast")
                    {
                        x = new XElement("preisVon", "Gast");
                        xx = new XElement("anzeigePreis", p3.Gastbetrag.ToString("C"));
                    }
                }
                else
                {
                    x = new XElement("preisVon", "Gast");
                    xx = new XElement("anzeigePreis", p3.Gastbetrag.ToString("C"));
                }
                v.Add(x);
                v.Add(xx);

                x = new XElement("beschreibung", p1.Beschreibung);
                v.Add(x);
                x = new XElement("titel", p1.Beschreibung);
                v.Add(x);

            }

            l = q.ToList();
            ViewBag.xml = l;
        
            

            return View();

         
        }


        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JP/DBWT Paket 5/DBWT Paket 5/Controllers/LoginController.cs
using DBWT_Paket_5.Models;
using System.Web.Mvc;
namespace DBWT_Paket_5.Controllers
{
    public class LoginController : Controller
    {
      
     
        // GET: /User/
        [HttpPost]
        public ActionResult login()
        {
            Login test = new Login();
            var name = Request["username"];
            var password = Request["password"];
            bool success = false;
            success = Login.login(password, name);
            bool aktiv = false;
            aktiv = test.isactiv(name.ToString());
            if (!aktiv) { return View("~/Views/Login/NotActive.cshtml"); }
            if (success == true)
            {

                Session["name"] = name;
                Session["role"] = Login.rolle(name);
                Benutzer ben1 = new Benutzer();
                ben1.LetzterLogin = ben1.GetLetzterLogin(Session["name"].ToString());
                ben1.SetLetzterLogin(name);
                return View("~/Views/Login/SuccessView.cshtml", model: ben1);
            }
         
            return View("~/Views/Login/FailedView.cshtml");
        }


        public ActionResult IndexLogin()
        {
          
            return View();
        }

        // GET: Login
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }

     

        // GET: Login
      
    }
}

JP/DBWT Paket 5/DBWT Paket 5/Controllers/ProdukteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBWT_Paket_5.Models;
namespace DBWT_Paket_5.Controllers
{
    public class ProdukteController : Controller
    {
        // GET: Produkte
        public ActionResult IndexProdukte(string id)
        {
          
            
            
            int t = 0;
            if (id != "") {
                t = Convert.ToInt32(id);
            }
       //     var kats = Produkt.kats();
            var p = Produkt.produktnachkat(t);
            kategorien k = new kategorien();
            var z = k.getkats();
            ViewData["kats"] = z;
        
            ViewData["MyP"] = p;
            return View();
        }
        public ActionResult ProduktenachKats(string id)
        {
            int t = Convert.ToInt32(id);
            var p = Produkt.produktnachkat(t);
            ViewData["MyP"] = p;
            return View();
        }
        // GET: Produkte/Details/5
        public ActionResult Details(string id)
        {
            int t = Convert.ToInt32(id);
            var p = Produkt.detail(t);
            ViewData["MyP"] = p;
            return View();
        }

        // GET: Produkte/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produkte/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produkte/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Produkte/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produkte/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Produkte/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

JP/DBWT Paket 5/DBWT Paket 5/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBWT_Paket_5.Models;

namespace DBWT_Paket_5
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            if (!string.IsNullOrEmpty(Session["user"] as string))
            {
                return View("~/View/Register/Fail.cshtml"); //Wenn die Registrieungsseite irgendwie geöffnet wird, wenn jemand angemeldet ist: Fehlerseite.
            }
            else
            {
                Register reg = new Register();
                return View(reg);
            }
        }

        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            if (!string.IsNullOrEmpty(Session["user"] as string))
            {
                return View("~/View/Register/Fail.cshtml"); //Wenn die Registrieungsseite irgendwie geöffnet wird, wenn jemand angemeldet ist: Fehlerseite.
            }
            else
            {
                Register reg = new Register();

                if (!string.IsNullOrEmpty(collection["rolle"])) //Ist eine Rolle gewählt worden?
                {
                    reg.rolle_pruefen_setzen(collection["rolle"], reg); // Ja, dann speichere die Rolle
                }
                else
                {
                    return View(reg); // nein, dann zeig Schritt 1 der Registrierung nochmal an.
                }

                reg.vorname = collection["vorname"];
                reg.nachname = collection["nachname"];
                reg.matrikelnummer = Convert.ToInt32(collection["matrikel"]);
                reg.studiengang = collection["studiengang"];
                reg.telefonnummer = collection["telefon"];
                reg.buero = collection["buero"];
                reg.grund = collection["grund"];

                reg.benutzername = collection["loginname"]; //überprüfen
                reg.email = collection["email"]; //überprüfen

                if (!reg.eingabe_korret(collection["passwort1"], collection["passwort2"], collection["loginname"], collection["email"], reg))
                {
                    return View(reg); // etwas war noch nicht korrekt, erfolgreich darf noch nicht true sein. die View wird nochmal mit alert aufgerufen.
                }

                if (collection["schritt2"] == "true")
                {
                    reg.erfolgreich = true;
                    reg.Nutzer_Anlegen();
                }
                return View(reg);
            }
        }
    }
}

JP/DBWT Paket 5/DBWT Paket 5/Views/Home/Backend.cshtml
@{
    ViewBag.Title = "Backend";
    Layout = "~/Views/Shared/_BELayout.cshtml";
}
@model DBWT_Paket_5.Models.Benutzer
<main class="row">

    <div class="col-md-2"></div>

    <div class="col-md-8">


        <div class="row margTop20px margBot10px">
            <h2>
                Letzte Anmeldungen
            </h2>

            <table class="table">
                <tr>
                    <th class="width25p">Zeitpunkt</th>
                    <th class="width55p">Loginname (Email)</th>
                    <th class="width20p">Aktion</th>
                </tr>

                @{
                   

                    if (true)
                    {

                        foreach (var f in ViewBag.llogin_rollen)
                        {
                            <tr>
                                <td>@f.LetzterLogin</td>
                                <td>@f.Loginname (@f.Email)</td>
                                <td>
                                    @{
                                        if ((bool)f.Aktiv)
                                        {
                                          
                                            @Html.ActionLink("deaktivieren", "deaktivieren", "Home", new { id = f.NR }, null)
                                        }
                                        else
                                        {
                                            
                                            @Html.ActionLink("aktivieren", "aktivieren", "Home", new { id = f.NR }, null)
                                        }
                                    }
                                </td>
                            </tr>
                                            }
                                        }
                }

            </table>
        </div>

        <div class="row margBot20px">
            <h2>
                Letzte Registrierungen
            </h2>

            <table class="table">
                <tr>
                    <th class="width25p">Datum</th>
                    <th class="width55p">Loginname (Email)</th>
                    <th class="width20p">Aktion</th>
                </tr>

                @{
                 //   l = ViewBag.lregistrierung;

                    if (true)
                    {
                        foreach (var f in ViewBag.lregistrierung_rollen)
                        {
                            <tr>
                                <td>@f.Anlegedatum</td>
                                <td>@f.Loginname (@f.Email)</td>
                                <td>
                                    @{
                                        if ((bool)f.Aktiv)
                                        {
                                      
                                            @Html.ActionLink("deaktivieren", "deaktivieren", "Home", new { id = f.NR }, null)
                                        }
                                        else
                                        {
                                      
                                            @Html.ActionLink("aktivieren", "aktivieren", "Home", new { id = f.NR }, null)
                                        }
                                    }
                                </td>
                            </tr>
                                            }
                                        }
                }
            </table>
        </div>

    </div>
    @using (Html.BeginForm("Logout", "Login", FormMethod.Post, new { @class = "form-horizontal" }))
            {
        <button type="submit" class="btn btn-default">Abmelden</button>
    }
    <div class="col-md-2"></div>

</main>

JP/DBWT Paket 5/DBWT Paket 5/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

@using MySql.Data.MySqlClient;
@using System.Configuration;


@functions
{

    public static string BlobToBase64(object b)
    {
        byte[] bytes = (byte[])b;
        if (bytes != null)
        {
            return Convert.ToBase64String(bytes);
        }
        return "";
    }

}
<html>
<head>
    <title></title>
</head>
<body>
    <div class="container">
        <div class="row">

            <div class="col-md-12">
                @{
                    const string constring = "Server=localhost;Database=praktikum;Uid=webapp;Pwd=webapp;";
                    MySqlConnection con = new MySqlConnection(constring);
                    con.Open();
                    MySqlCommand cmd;
                    cmd = con.CreateCommand();
                    cmd.CommandText = "select bild.id, bild.Binaerdaten as b from bild where bild.id =9";
                    MySqlDataReader r = cmd.ExecuteReader();

                    r.Read();
                    string base64text = BlobToBase64(r["b"]);


                }

                <img src="data:image/png;base64,@base64text" alt="Mensa" class="img-rounded" />
                @{
                    con.Close();
                    r.Close();
                }
            </div>

        </div>
        <div class="col-md-3">
            <h4>
                Der Dienst <b>e-Mensa</b> ist <br />
                noch beta. Sie können <br />
                bereits <a href="@Url.Action("IndexProdukte", "Produkte")" style="text-decoration:underline">Mahlzeiten</a> <br />
                durchstöbern, aber noch nicht bestellen.
            </h4>
        </div>
        <div class="col-md-7">
            <h1>Leckere Gerichte vorbestellen</h1><br />
            <h4>... und gemeinsam mit Kommilitonen und Freunden essen</h4>
        </div>
        <div class="col-md-2">
            <br />
            @using (Html.BeginForm("IndexLogin", "Login", FormMethod.Get, new { @class = "form-horizontal" }))
            {
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-hand-right"> Anmelden</span></button>
            }

            @using (Html.BeginForm("Index", "Register", FormMethod.Get, new { @class = "form-horizontal" }))
            {
                <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-hand-right"> Registrieren</span></button>
            }
        </div>
        <div class="col-md-3">
            <h4>
                Registrieren Sie sich <br />
                <a href="@Url.Action("Index", "Register")" style="text-decoration:underline">hier</a> um über die<br />
                Veröffentlichung des Dienstes per Mail <br />
                informiert zu werden.
            </h4>
        </div>
        <div class="col-md-9">
            <img src="data:image/png;base64,@base64text" alt="Mensa" class="img-rounded" />

        </div>

    </div>

</body>
</html>

JP/DBWT Paket 5/DBWT Paket 5/Views/Home/xmlsite.cshtml
@{
    ViewBag.Title = "xmlsite";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-2"></div>
<div class="col-md-8">

    @{

        List<System.Xml.Linq.XElement> l = new List<System.Xml.Linq.XElement>();
        int i = 1;
        if (ViewBag.xml != null)
        {
            l = ViewBag.xml;
        }

        foreach (var v in l)
        {
            <div class="row margTop20px margBot10px">

                @if (DateTimeOffset.Parse(v.Attribute("Tag").Value).Date == DateTimeOffset.Now.Date)
                {
                    <h3>Heutiges Menü: @v.Element("Motto").Value (KW @v.Attribute("Kalenderwoche").Value)</h3>
                }
                else
                {
                    <h3>@DateTimeOffset.Parse(v.Attribute("Tag").Value).Date.ToString("d") Menü: @v.Element("Motto").Value (KW @v.Attribute("Kalenderwoche").Value)</h3>
                }

                <table class="table margBot10px">
                    <tr>
                        <th class="width10p">Typ</th>
                        <th class="width50p">Mahlzeit</th>
                        <th class="width10p">Preis</th>
                        @if (v.Attribute("Highlight") != null)
                        {
                            <th class="width20p">Bild</th>
                        }
                        else
                        {
                            <th class="width20p"></th>
                        }

                    </tr>

                    @foreach (var vv in v.Element("Produkte").Elements("Produkt"))
                    {
                        <tr>
                            <td>@vv.Attribute("Typ").Value.ToString()</td>
                            <td>
                                <h4>@vv.Element("titel").Value</h4>
                                <p>@vv.Element("beschreibung").Value</p>
                            </td>
                            <td>@vv.Element("anzeigePreis").Value (@vv.Element("preisVon").Value)</td>
                            <td>
                                @if (vv.Element("Bild") != null)
                                {
                                    <img src="data:image/png;base64,@vv.Element("Bild").Value" alt="Err" class="thumbnail imgDetails imgProdukteDetails">
                                }
                            </td>
                        </tr>
                    }

                </table>
            </div>
        }
    }
</div>